version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.20.0.2
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: myapp
    networks:
      app_net:
        ipv4_address: 172.20.0.3

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
